# Default configuration for Financial ML Pipeline

# Data settings
data: "data/full_data.csv"
seed: 42
desired_num_bars: 100000

# Labeling parameters
pt: 2.0    # Profit taking multiplier
sl: 2.0    # Stop loss multiplier
vertical: 12  # Number of bars for vertical barrier

# Model optimization
n_trials: 30   # Number of Optuna trials
n_splits: 4    # Number of CV splits
train_size: 0.8  # Fraction of data for training

# Backtesting parameters
initial_capital: 100000.0  # Starting capital for backtesting
transaction_cost_pct: 0.001  # Transaction cost as percentage (0.1%)
long_only: false  # If true, treat sell signals as exit signals
risk_fraction: 1  # Risk fraction for backtesting


# Optional: Pre-configured hyperparameters (set to null to use Optuna)
# hyperparameters:
#   n_estimators: null
#   learning_rate: null
#   num_leaves: null
#   max_depth: null
#   lambda_l1: null
#   lambda_l2: null
#   feature_fraction: null
#   bagging_fraction: null
#   bagging_freq: null
#   min_child_samples: null

hyperparameters:
  n_estimators: 447
  learning_rate: 0.08013346658513963
  num_leaves: 98
  max_depth: 11
  lambda_l1: 0.24403964410827697
  lambda_l2: 2.9121726876229024e-07
  feature_fraction: 0.6493417133734326
  bagging_fraction: 0.5088127802517731
  bagging_freq: 1
  min_child_samples: 39